In [1]:
import numpy as np
from keras.utils import np_utils
import tensorflow as tf
# Using TensorFlow 1.0.0; use tf.python_io in later versions
tf.python.control_flow_ops = tf

# Set random seed
np.random.seed(42)

# Our data
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')



Using TensorFlow backend.


In [3]:
print(X)
print(y)



[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
[[0.]
 [1.]
 [1.]
 [0.]]


In [4]:
# Initial Setup for Keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation
# One-hot encoding the output
y = np_utils.to_categorical(y)
print(y)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]


In [5]:


# Building the model
xor = Sequential()

# Add required layers
xor.add(Dense(8, input_dim=X.shape[1]))
xor.add(Activation("tanh"))
xor.add(Dense(2))
xor.add(Activation("sigmoid"))

# Specify loss as "binary_crossentropy", optimizer as "adam",
# and add the accuracy metric
xor.compile(loss="binary_crossentropy", optimizer="adam", metrics = ["accuracy"])


# Uncomment this line to print the model architecture
xor.summary()


def model_op(mod):
  k = {}
  for a in range(100,1600,200):
    history = mod.fit(X, y, nb_epoch=a)
    score = mod.evaluate(X, y)
    m = {a: score[-1]}
    k.update(m)
  return k

dict_accuracy = model_op(xor)









Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 24        
_________________________________________________________________
activation_1 (Activation)    (None, 8)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 18        
_________________________________________________________________
activation_2 (Activation)    (None, 2)                 0         
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.




Epoch 1/100





4/4 [==============================] - 1s 226ms/step - loss: 0.7566 - acc: 0.6250
Epoch 2/100
4/4 [==============================] - 0s 553us/step - loss: 0.7559 - acc: 0.6250
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 0.7551 - acc: 0.6250
Epoch 4/100
4/4 [==============================] - 0s 531us/step - loss: 0.7542 - acc: 0.6250
Epoch 5/100
4/4 [==============================] - 0s 467us/step - loss: 0.7534 - acc: 0.6250
Epoch 6/100
4/4 [==============================] - 0s 449us/step - loss: 0.7526 - acc: 0.6250
Epoch 7/100
4/4 [==============================] - 0s 433us/step - loss: 0.7517 - acc: 0.6250
Epoch 8/100
4/4 [==============================] - 0s 461us/step - loss: 0.7509 - acc: 0.6250
Epoch 9/100
4/4 [==============================] - 0s 460us/step - loss: 0.7501 - acc: 0.6250
Epoch 10/100
4/4 [==============================] - 0s 469us/step - loss: 0.7492 - acc: 0.6250
Epoch 11/100
4/4 [==============================] - 0s

In [23]:
print(dict_accuracy)
m = [k for k,v in dict_accuracy.items() if v==max(dict_accuracy.items())[1]][0]
print(m)

{100: 0.5, 300: 0.5, 500: 1.0, 700: 1.0, 900: 1.0, 1100: 1.0, 1300: 1.0, 1500: 1.0}
500


In [24]:
# Fitting the model
history = xor.fit(X, y, nb_epoch=m, verbose=0)

# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1])


# Checking the predictions
print("\nPredictions:")
print(xor.predict_proba(X))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


4/4 [==============================] - 0s 123us/step

Accuracy:  1.0

Predictions:
[[9.9967158e-01 2.7650595e-04]
 [7.7742338e-04 9.9842823e-01]
 [3.5563111e-04 9.9930668e-01]
 [9.9939728e-01 1.3882816e-03]]
